# -*- coding: utf-8 -*-
"""Donghyeon 124

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O2cFevKE9j-868lcw6Lv3zb5pBQe9vtG

### 1.편의점 매출 계산하기
"""

yogurt = (1300-480)*3
gimbab = (2500-900)*5*0.85
coke = (800-380)*6*0.85
banana = (3200-1050)*2
snack = (1500-770)*4

total_fee = yogurt + gimbab + coke + banana + snack
print(f'총 매출액은 {int(total_fee)}원입니다')

"""### 2. 흙을 나르는 마이클"""

import random
n = random.randint(10, 100)
print(f'n이{n}일 때 : ')
i = 0
j = 0
while n >= 5:
  n = n-5
  i += 1
else :
   while n >=3:
     n = n-3
     j += 1
   else :
     if n%3 == 0:
       j = j
     else :
       j += 1
      


print(f' 5kg:{i}번 3kg:{j}번 입니다.')

"""### 4. 세 수 중 가장 큰 수 찾기

"""

a = int(input("첫 번째 수를 입력해주세요 : "))
b = int(input("두 번째 수를 입력해주세요 : "))
c = int(input("세 번째 수를 입력해주세요 : "))

if a > b:
    if a > c:
        max = a
    else :
        max = c
else :
    if b > c:
      max = b
    else : 
      max = c
      
print(f'세 수중 가장 큰 수는 {max}입니다')

